### ISSUE TITLE
Drupal 8.8.1 "No check has been registered for access_check.permission" at CheckProvider.php line 97

### ISSUE THREAD

**Issue by csandanov** [drupal-composer/drupal-composer-project#541]
## Issue

I'm not entirely sure this issue has anything to do with this composer project or it's just a Drupal core issue. So if you think it's definitely not, feel free to close this issue (I've already [posted](https://drupal.stackexchange.com/questions/289480/class-drupal-system-controller-http4xxcontroller-does-not-exist) it to drupal.stackexchange.com) 

I'm using this composer project with the only one modification – I freeze Drupal core in `composer.json`. And since the core version has been updated to 8.8.1 I get the following errors after installing Drupal from a browser.

```php
Uncaught PHP Exception InvalidArgumentException: "Class "\Drupal\system\Controller\Http4xxController" does not exist." at /var/www/html/web/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php line 24
Uncaught PHP Exception InvalidArgumentException: "No check has been registered for access_check.permission" at /var/www/html/web/core/lib/Drupal/Core/Access/CheckProvider.php line 97
```

This happens on PHP 7.2 and 7.3 (latest patches 7.2.26, 7.3.13). 

## Steps to reproduce:
1. Clone https://github.com/wodby/docker4drupal
2. Update `DRUPAL_TAG` in `.env` to `8-7.2` or `8-7.3`
3. Run `make` (you'll need docker running)
4. Give it a few seconds for containers to start
5. Go to `drupal.docker.localhost:8000` (if you're not on chrome, you have to add it to `/etc/hosts`)
6. Install Drupal as usual with a standard profile
7. You should get `The website encountered an unexpected error. Please try again later.` after finishing the installation

It seems there's something with the dependency injection container because such class within the namespace exists.  What's interesting is that this issue does not happen with Drupal core 8.8.0 with the same PHP versions.

**Comment by drakythe** [comment]
My team and I are experiencing this as well, while using DDEV. We've taken to downloading everything and up changing the composer.json to remove the "^" from in front of all the drupal core reqs, delete composer.lock, and then remove the Web dir and run "composer install" to get drupal 8.8.0. Then run your install and after you get to the drupal site you can run your composer update to get to 8.8.1.

Not perfect, but until this 8.8.1 install bug is resolved its the best we have.

**Comment by csandanov** [comment]
Ref issue on drupa.org https://www.drupal.org/project/drupal/issues/3103529

**Comment by csandanov** [comment]
Actually, this issue happens even without any modifications of composer.json with the latest PHP 7.3, just using plain drupal-composer causes this WSOD. This how I install it.

```
composer create-project drupal-composer/drupal-project:8.x-dev /usr/src/drupal --stability dev --no-interaction --no-install
cd /usr/src/drupal 
composer install
```
I don't get class not exists error but I still get:
```
Uncaught PHP Exception InvalidArgumentException: "No check has been registered for access_check.permission" at /var/www/html/web/core/lib/Drupal/Core/Access/CheckProvider.php line 97
```

**Comment by normanlolx** [comment]
Has been fixed by core https://www.drupal.org/project/drupal/issues/3103529.
